language: csharp
mono: none
group: dev
sudo: required
dist: xenial
dotnet: 2.2

jobs:
  include:
    - stage: build
      script: 
        - dotnet build Cloo/Cloo.csproj
        - dotnet build ClootilsNetCore/ClootilsNetCore.csproj
        - dotnet build ClootilsNetCoreUI/ClootilsNetCoreUI.csproj
    - stage: deploy
      if: branch = master AND tag IS present
      script:
        - dotnet pack Cloo/Cloo.csproj --configuration Release      
      deploy:
        - provider: script
          skip_cleanup: true
          script: dotnet nuget push Cloo/bin/Release/Cloo.clSharp.*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
        - provider: releases
          api_key: $GITHUB_TOKEN
          skip_cleanup: false

