using System;
namespace OpenTK.Compute
{
    public class ComputeException: Exception { }
    public class DeviceNotFoundException: ComputeException { }
    public class DeviceNotAvailableException: ComputeException { }
    public class CompilerNotAvailableException: ComputeException { }
    public class BufferAllocationException: ComputeException { }
    public class OutOfResourcesException: ComputeException { }
    public class OutOfHostMemoryException: ComputeException { }
    public class ProfilingInfoNotAvailableException: ComputeException { }
    public class MemoryCopyOverlapException: ComputeException { }
    public class ImageFormatMismatchException: ComputeException { }
    public class ImageFormatNotSupportedException: ComputeException { }
    public class BuildProgramFailureException: ComputeException { }
    public class MapFailureException: ComputeException { }
    public class InvalidValueException: ComputeException { }
    public class InvalidDeviceTypeException: ComputeException { }
    public class InvalidPlatformException: ComputeException { }
    public class InvalidDeviceException: ComputeException { }
    public class InvalidContextException: ComputeException { }
    public class InvalidQueuePropertiesException: ComputeException { }
    public class InvalidCommandQueueException: ComputeException { }
    public class InvalidHostPointerException: ComputeException { }
    public class InvalidBufferException: ComputeException { }
    public class InvalidImageFormatDescriptorException: ComputeException { }
    public class InvalidImageSizeException: ComputeException { }
    public class InvalidSamplerException: ComputeException { }
    public class InvalidBinaryException: ComputeException { }
    public class InvalidBuildOptionsException: ComputeException { }
    public class InvalidProgramException: ComputeException { }
    public class InvalidProgramExecutableException: ComputeException { }
    public class InvalidKernelNameException: ComputeException { }
    public class InvalidKernelDefinitionException: ComputeException { }
    public class InvalidKernelException: ComputeException { }
    public class InvalidArgumentIndexException: ComputeException { }
    public class InvalidArgumentValueException: ComputeException { }
    public class InvalidArgumentSizeException: ComputeException { }
    public class InvalidKernelArgumentsException: ComputeException { }
    public class InvalidWorkDimensionsException: ComputeException { }
    public class InvalidWorkGroupSizeException: ComputeException { }
    public class InvalidWorkItemSizeException: ComputeException { }
    public class InvalidGlobalOffsetException: ComputeException { }
    public class InvalidEventWaitListException: ComputeException { }
    public class InvalidEventException: ComputeException { }
    public class InvalidOperationException: ComputeException { }
    public class InvalidGraphicsObjectException: ComputeException { }
    public class InvalidBufferSizeException: ComputeException { }
    public class InvalidMipLevelException: ComputeException { }
}